### ISSUE TITLE
Error while compiling project

### ISSUE THREAD

**Issue by remaker17** [evant/kotlin-inject#348] opened 2024-02-05 23:14 UTC
```
Task :app:kspDebugKotlin
e: [ksp] java.lang.IllegalArgumentException: Error type '<ERROR TYPE>' is not resolvable in the current round of processing.
	at com.squareup.kotlinpoet.ksp.KsTypesKt.toTypeName(KsTypes.kt:61)
	at com.squareup.kotlinpoet.ksp.KsTypesKt.toTypeName(KsTypes.kt:182)
	at com.squareup.kotlinpoet.ksp.KsTypesKt.toTypeName(KsTypes.kt:167)
	at com.squareup.kotlinpoet.ksp.KsTypesKt.toTypeName(KsTypes.kt:66)
	at com.squareup.kotlinpoet.ksp.KsTypesKt.toTypeName(KsTypes.kt:182)
	at com.squareup.kotlinpoet.ksp.KsTypesKt.toTypeName$default(KsTypes.kt:179)
	at me.tatarka.kotlin.ast.KSAstType.toString(KSAst.kt:455)
	at java.base/java.lang.StringConcatHelper.stringOf(StringConcatHelper.java:453)
	at me.tatarka.kotlin.ast.KSAstParam.toString(KSAst.kt:486)
	at java.base/java.lang.String.valueOf(String.java:4215)
	at kotlin.text.StringsKt__AppendableKt.appendElement(Appendable.kt:88)
	at kotlin.collections.CollectionsKt___CollectionsKt.joinTo(_Collections.kt:3490)
	at kotlin.collections.CollectionsKt___CollectionsKt.joinToString(_Collections.kt:3507)
	at kotlin.collections.CollectionsKt___CollectionsKt.joinToString$default(_Collections.kt:3506)
	at me.tatarka.kotlin.ast.AstConstructor.toString(Ast.kt:123)
	at java.base/java.lang.StringConcatHelper.stringOf(StringConcatHelper.java:453)
	at me.tatarka.kotlin.ast.KSAstProvider.toTrace(KSAst.kt:78)
	at me.tatarka.inject.compiler.CycleDetector$trace$2.invoke(CycleDetector.kt:72)
	at me.tatarka.inject.compiler.CycleDetector$trace$2.invoke(CycleDetector.kt:72)
	at kotlin.text.StringsKt__AppendableKt.appendElement(Appendable.kt:85)
	at kotlin.collections.CollectionsKt___CollectionsKt.joinTo(_Collections.kt:3490)
	at kotlin.collections.CollectionsKt___CollectionsKt.joinToString(_Collections.kt:3507)
	at kotlin.collections.CollectionsKt___CollectionsKt.joinToString$default(_Collections.kt:3506)
	at me.tatarka.inject.compiler.CycleDetector.trace(CycleDetector.kt:72)
	at me.tatarka.inject.compiler.TypeResultResolver.trace(TypeResultResolver.kt:558)
	at me.tatarka.inject.compiler.TypeResultResolver.findType(TypeResultResolver.kt:193)
	at me.tatarka.inject.compiler.TypeResultResolver.resolveOrNull(TypeResultResolver.kt:49)
	at me.tatarka.inject.compiler.TypeResultResolver.findType(TypeResultResolver.kt:229)
	at me.tatarka.inject.compiler.TypeResultResolver.resolveOrNull(TypeResultResolver.kt:49)
	at me.tatarka.inject.compiler.TypeResultResolver.resolveParamsLegacy(TypeResultResolver.kt:160)
	at me.tatarka.inject.compiler.TypeResultResolver.resolveParams(TypeResultResolver.kt:70)
	at me.tatarka.inject.compiler.TypeResultResolver.access$resolveParams(TypeResultResolver.kt:17)
	at me.tatarka.inject.compiler.TypeResultResolver$Constructor$1.invoke(TypeResultResolver.kt:452)
	at me.tatarka.inject.compiler.TypeResultResolver$Constructor$1.invoke(TypeResultResolver.kt:448)
	at me.tatarka.inject.compiler.TypeResultResolver$withCycleDetection$result$1.invoke(TypeResultResolver.kt:537)
	at me.tatarka.inject.compiler.TypeResultResolver$withCycleDetection$result$1.invoke(TypeResultResolver.kt:535)
	at me.tatarka.inject.compiler.CycleDetector.check(CycleDetector.kt:53)
	at me.tatarka.inject.compiler.TypeResultResolver.withCycleDetection(TypeResultResolver.kt:535)
	at me.tatarka.inject.compiler.TypeResultResolver.Constructor(TypeResultResolver.kt:448)
	at me.tatarka.inject.compiler.TypeResultResolver.constructor(TypeResultResolver.kt:379)
	at me.tatarka.inject.compiler.TypeResultResolver.findType(TypeResultResolver.kt:236)
	at me.tatarka.inject.compiler.TypeResultResolver.resolveOrNull(TypeResultResolver.kt:49)
	at me.tatarka.inject.compiler.TypeResultResolver.resolveParamsLegacy(TypeResultResolver.kt:160)
	at me.tatarka.inject.compiler.TypeResultResolver.resolveParams(TypeResultResolver.kt:70)
	at me.tatarka.inject.compiler.TypeResultResolver.access$resolveParams(TypeResultResolver.kt:17)
	at me.tatarka.inject.compiler.TypeResultResolver$Provides$1.invoke(TypeResultResolver.kt:426)
	at me.tatarka.inject.compiler.TypeResultResolver$Provides$1.invoke(TypeResultResolver.kt:415)
	at me.tatarka.inject.compiler.TypeResultResolver$withCycleDetection$result$1.invoke(TypeResultResolver.kt:537)
	at me.tatarka.inject.compiler.TypeResultResolver$withCycleDetection$result$1.invoke(TypeResultResolver.kt:535)
	at me.tatarka.inject.compiler.CycleDetector.check(CycleDetector.kt:53)
	at me.tatarka.inject.compiler.TypeResultResolver.withCycleDetection(TypeResultResolver.kt:535)
	at me.tatarka.inject.compiler.TypeResultResolver.Provides(TypeResultResolver.kt:415)
	at me.tatarka.inject.compiler.TypeResultResolver.method(TypeResultResolver.kt:256)
	at me.tatarka.inject.compiler.TypeResultResolver.findType(TypeResultResolver.kt:211)
	at me.tatarka.inject.compiler.TypeResultResolver.resolveOrNull(TypeResultResolver.kt:49)
	at me.tatarka.inject.compiler.TypeResultResolver.resolve(TypeResultResolver.kt:39)
	at me.tatarka.inject.compiler.TypeResultResolver.Scoped(TypeResultResolver.kt:440)
	at me.tatarka.inject.compiler.TypeResultResolver.method(TypeResultResolver.kt:248)
	at me.tatarka.inject.compiler.TypeResultResolver.findType(TypeResultResolver.kt:211)
	at me.tatarka.inject.compiler.TypeResultResolver.resolveOrNull(TypeResultResolver.kt:49)
	at me.tatarka.inject.compiler.TypeResultResolver.resolve(TypeResultResolver.kt:39)
	at me.tatarka.inject.compiler.TypeResultResolver.access$resolve(TypeResultResolver.kt:17)
	at me.tatarka.inject.compiler.TypeResultResolver$Provider$result$1.invoke(TypeResultResolver.kt:396)
	at me.tatarka.inject.compiler.TypeResultResolver$Provider$result$1.invoke(TypeResultResolver.kt:395)
	at me.tatarka.inject.compiler.TypeResultResolver$withCycleDetection$result$1.invoke(TypeResultResolver.kt:537)
	at me.tatarka.inject.compiler.TypeResultResolver$withCycleDetection$result$1.invoke(TypeResultResolver.kt:535)
	at me.tatarka.inject.compiler.CycleDetector.check(CycleDetector.kt:53)
	at me.tatarka.inject.compiler.TypeResultResolver.withCycleDetection(TypeResultResolver.kt:535)
	at me.tatarka.inject.compiler.TypeResultResolver.Provider(TypeResultResolver.kt:395)
	at me.tatarka.inject.compiler.TypeResultResolver.resolveAll(TypeResultResolver.kt:30)
	at me.tatarka.inject.compiler.InjectGenerator.generateInjectComponent(InjectGenerator.kt:140)
	at me.tatarka.inject.compiler.InjectGenerator.generate(InjectGenerator.kt:60)
	at me.tatarka.inject.compiler.ksp.InjectProcessor.process(InjectProcessor.kt:64)
	at me.tatarka.inject.compiler.ksp.InjectProcessor.process(InjectProcessor.kt:52)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension$doAnalysis$8$1.invoke(KotlinSymbolProcessingExtension.kt:306)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension$doAnalysis$8$1.invoke(KotlinSymbolProcessingExtension.kt:304)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension.handleException(KotlinSymbolProcessingExtension.kt:410)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension.doAnalysis(KotlinSymbolProcessingExtension.kt:304)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration(TopDownAnalyzerFacadeForJVM.kt:112)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration$default(TopDownAnalyzerFacadeForJVM.kt:77)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:256)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:247)
	at org.jetbrains.kotlin.cli.common.messages.AnalyzerWithCompilerReport.analyzeAndReport(AnalyzerWithCompilerReport.kt:115)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.analyze(KotlinToJVMBytecodeCompiler.kt:247)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:87)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli$default(KotlinToJVMBytecodeCompiler.kt:43)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:165)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:50)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:104)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:48)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:101)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1523)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:360)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
	at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:587)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:828)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:705)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:704)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by evant** [comment] 2024-02-06 01:34
Looks like it's failing to resolve a type, any chance you can come up with a small sample that reproduces the issue?

**Comment by remaker17** [comment] 2024-02-06 04:10
[repository where it's failing](https://github.com/remaker17/CosmicIdeQ)

**Comment by evant** [comment] 2024-02-06 18:25
If you comment out the kotlin-inject processor there appears to be other build errors which I suspect is your issue. Still marking this as a bug because it's supposed to skip processing in this case so it doesn't cover up your original errors.

```
> Task :app:compileDebugKotlin FAILED
e: file:///Users/evatatarka/personal/CosmicIdeQ/app/src/main/kotlin/dev/remaker/cosmicideq/IdeApplication.kt:11:38 Unresolved reference: create
e: file:///Users/evatatarka/personal/CosmicIdeQ/app/src/main/kotlin/dev/remaker/cosmicideq/IdeApplication.kt:14:49 Property delegate must have a 'getValue(IdeApplication, KProperty<*>)' method. None of the following functions is suitable:
public inline operator fun <T> Lazy<Unit>.getValue(thisRef: Any?, property: KProperty<*>): Unit defined in kotlin
e: file:///Users/evatatarka/personal/CosmicIdeQ/app/src/main/kotlin/dev/remaker/cosmicideq/IdeApplication.kt:15:33 Unresolved reference: create
e: file:///Users/evatatarka/personal/CosmicIdeQ/app/src/main/kotlin/dev/remaker/cosmicideq/IdeApplication.kt:21:15 Unresolved reference: initializers
e: file:///Users/evatatarka/personal/CosmicIdeQ/app/src/main/kotlin/dev/remaker/cosmicideq/IdeContent.kt:36:33 Unresolved reference: remember
e: file:///Users/evatatarka/personal/CosmicIdeQ/app/src/main/kotlin/dev/remaker/cosmicideq/IdeContent.kt:37:5 @Composable invocations can only happen from the context of a @Composable function
e: file:///Users/evatatarka/personal/CosmicIdeQ/app/src/main/kotlin/dev/remaker/cosmicideq/IdeContent.kt:40:3 Unresolved reference: CompositionLocalProvider
e: file:///Users/evatatarka/personal/CosmicIdeQ/app/src/main/kotlin/dev/remaker/cosmicideq/IdeContent.kt:41:5 Unresolved reference: CircuitCompositionLocals
e: file:///Users/evatatarka/personal/CosmicIdeQ/app/src/main/kotlin/dev/remaker/cosmicideq/IdeContent.kt:42:7 @Composable invocations can only happen from the context of a @Composable function
e: file:///Users/evatatarka/personal/CosmicIdeQ/app/src/main/kotlin/dev/remaker/cosmicideq/IdeContent.kt:43:37 @Composable invocations can only happen from the context of a @Composable function
e: file:///Users/evatatarka/personal/CosmicIdeQ/app/src/main/kotlin/dev/remaker/cosmicideq/IdeContent.kt:44:40 @Composable invocations can only happen from the context of a @Composable function
e: file:///Users/evatatarka/personal/CosmicIdeQ/app/src/main/kotlin/dev/remaker/cosmicideq/IdeContent.kt:61:11 'val' on function parameter is not allowed
e: file:///Users/evatatarka/personal/CosmicIdeQ/app/src/main/kotlin/dev/remaker/cosmicideq/IdeContent.kt:62:11 'val' on function parameter is not allowed
e: file:///Users/evatatarka/personal/CosmicIdeQ/app/src/main/kotlin/dev/remaker/cosmicideq/IdeContent.kt:64:3 Modifier 'override' is not applicable to 'local function'
e: file:///Users/evatatarka/personal/CosmicIdeQ/app/src/main/kotlin/dev/remaker/cosmicideq/IdeContent.kt:68:3 Modifier 'override' is not applicable to 'local function'
e: file:///Users/evatatarka/personal/CosmicIdeQ/app/src/main/kotlin/dev/remaker/cosmicideq/IdeContent.kt:72:3 Modifier 'override' is not applicable to 'local function'
e: file:///Users/evatatarka/personal/CosmicIdeQ/app/src/main/kotlin/dev/remaker/cosmicideq/IdeContent.kt:75:1 A 'return' expression required in a function with a block body ('{...}')
e: file:///Users/evatatarka/personal/CosmicIdeQ/app/src/main/kotlin/dev/remaker/cosmicideq/MainActivity.kt:19:38 Unresolved reference: create
e: file:///Users/evatatarka/personal/CosmicIdeQ/app/src/main/kotlin/dev/remaker/cosmicideq/MainActivity.kt:33:46 Unresolved reference: create
e: file:///Users/evatatarka/personal/CosmicIdeQ/app/src/main/kotlin/dev/remaker/cosmicideq/MainActivity.kt:65:65 Unresolved reference: Context
e: file:///Users/evatatarka/personal/CosmicIdeQ/app/src/main/kotlin/dev/remaker/cosmicideq/settings/IdePreferencesImpl.kt:3:12 Unresolved reference: russhwolf
e: file:///Users/evatatarka/personal/CosmicIdeQ/app/src/main/kotlin/dev/remaker/cosmicideq/settings/IdePreferencesImpl.kt:4:12 Unresolved reference: russhwolf
e: file:///Users/evatatarka/personal/CosmicIdeQ/app/src/main/kotlin/dev/remaker/cosmicideq/settings/IdePreferencesImpl.kt:5:12 Unresolved reference: russhwolf
e: file:///Users/evatatarka/personal/CosmicIdeQ/app/src/main/kotlin/dev/remaker/cosmicideq/settings/IdePreferencesImpl.kt:6:12 Unresolved reference: russhwolf
e: file:///Users/evatatarka/personal/CosmicIdeQ/app/src/main/kotlin/dev/remaker/cosmicideq/settings/IdePreferencesImpl.kt:17:8 Unresolved reference: ExperimentalSettingsApi
e: file:///Users/evatatarka/personal/CosmicIdeQ/app/src/main/kotlin/dev/remaker/cosmicideq/settings/IdePreferencesImpl.kt:17:8 An annotation argument must be a compile-time constant
e: file:///Users/evatatarka/personal/CosmicIdeQ/app/src/main/kotlin/dev/remaker/cosmicideq/settings/IdePreferencesImpl.kt:20:15 Conflicting declarations: private final val settings: [Error type: Unresolved type for ObservableSettings], private final val settings: Lazy<[Error type: Unresolved type for ObservableSettings]>
e: file:///Users/evatatarka/personal/CosmicIdeQ/app/src/main/kotlin/dev/remaker/cosmicideq/settings/IdePreferencesImpl.kt:20:30 Unresolved reference: ObservableSettings
e: file:///Users/evatatarka/personal/CosmicIdeQ/app/src/main/kotlin/dev/remaker/cosmicideq/settings/IdePreferencesImpl.kt:23:15 Conflicting declarations: private final val settings: [Error type: Unresolved type for ObservableSettings], private final val settings: Lazy<[Error type: Unresolved type for ObservableSettings]>
e: file:///Users/evatatarka/personal/CosmicIdeQ/app/src/main/kotlin/dev/remaker/cosmicideq/settings/IdePreferencesImpl.kt:23:25 Unresolved reference: ObservableSettings
e: file:///Users/evatatarka/personal/CosmicIdeQ/app/src/main/kotlin/dev/remaker/cosmicideq/settings/IdePreferencesImpl.kt:23:47 Overload resolution ambiguity:
private final val settings: [Error type: Unresolved type for ObservableSettings] defined in dev.remaker.cosmicideq.settings.IdePreferencesImpl
private final val settings: Lazy<[Error type: Unresolved type for ObservableSettings]> defined in dev.remaker.cosmicideq.settings.IdePreferencesImpl
e: file:///Users/evatatarka/personal/CosmicIdeQ/app/src/main/kotlin/dev/remaker/cosmicideq/settings/IdePreferencesImpl.kt:24:31 Property delegate must have a 'getValue(IdePreferencesImpl, KProperty<*>)' method. None of the following functions is suitable:
public inline operator fun <T> Lazy<???>.getValue(thisRef: Any?, property: KProperty<*>): ??? defined in kotlin
e: file:///Users/evatatarka/personal/CosmicIdeQ/app/src/main/kotlin/dev/remaker/cosmicideq/settings/IdePreferencesImpl.kt:24:38 Overload resolution ambiguity:
private final val settings: [Error type: Unresolved type for ObservableSettings] defined in dev.remaker.cosmicideq.settings.IdePreferencesImpl
private final val settings: Lazy<[Error type: Unresolved type for ObservableSettings]> defined in dev.remaker.cosmicideq.settings.IdePreferencesImpl
e: file:///Users/evatatarka/personal/CosmicIdeQ/app/src/main/kotlin/dev/remaker/cosmicideq/settings/IdePreferencesImpl.kt:27:5 Overload resolution ambiguity:
private final val settings: [Error type: Unresolved type for ObservableSettings] defined in dev.remaker.cosmicideq.settings.IdePreferencesImpl
private final val settings: Lazy<[Error type: Unresolved type for ObservableSettings]> defined in dev.remaker.cosmicideq.settings.IdePreferencesImpl
e: file:///Users/evatatarka/personal/CosmicIdeQ/app/src/main/kotlin/dev/remaker/cosmicideq/settings/IdePreferencesImpl.kt:31:12 Overload resolution ambiguity:
private final val settings: [Error type: Unresolved type for ObservableSettings] defined in dev.remaker.cosmicideq.settings.IdePreferencesImpl
private final val settings: Lazy<[Error type: Unresolved type for ObservableSettings]> defined in dev.remaker.cosmicideq.settings.IdePreferencesImpl
e: file:///Users/evatatarka/personal/CosmicIdeQ/app/src/main/kotlin/dev/remaker/cosmicideq/settings/IdePreferencesImpl.kt:36:5 Overload resolution ambiguity:
private final val settings: [Error type: Unresolved type for ObservableSettings] defined in dev.remaker.cosmicideq.settings.IdePreferencesImpl
private final val settings: Lazy<[Error type: Unresolved type for ObservableSettings]> defined in dev.remaker.cosmicideq.settings.IdePreferencesImpl
e: file:///Users/evatatarka/personal/CosmicIdeQ/app/src/main/kotlin/dev/remaker/cosmicideq/settings/PreferencesComponent.kt:7:12 Unresolved reference: russhwolf
e: file:///Users/evatatarka/personal/CosmicIdeQ/app/src/main/kotlin/dev/remaker/cosmicideq/settings/PreferencesComponent.kt:8:12 Unresolved reference: russhwolf
e: file:///Users/evatatarka/personal/CosmicIdeQ/app/src/main/kotlin/dev/remaker/cosmicideq/settings/PreferencesComponent.kt:19:58 Unresolved reference: ObservableSettings
e: file:///Users/evatatarka/personal/CosmicIdeQ/app/src/main/kotlin/dev/remaker/cosmicideq/settings/PreferencesComponent.kt:20:12 Unresolved reference: SharedPreferencesSettings
e: file:///Users/evatatarka/personal/CosmicIdeQ/app/src/main/kotlin/dev/remaker/cosmicideq/ui/screen/install/InstallPresenter.kt:25:10 Unresolved reference: InstallScreen
e: file:///Users/evatatarka/personal/CosmicIdeQ/app/src/main/kotlin/dev/remaker/cosmicideq/ui/screen/projectlist/ProjectListPresenter.kt:23:10 Unresolved reference: ProjectListScreen
e: file:///Users/evatatarka/personal/CosmicIdeQ/app/src/main/kotlin/dev/remaker/cosmicideq/ui/screen/projectlist/ProjectListPresenter.kt:35:30 No value passed for parameter 'eventSink'

```

**Closed** 2024-02-07 03:26 UTC
Labels: bug
