### ISSUE TITLE
Annotation based multiple bindings support?

### ISSUE THREAD

**Issue by wsxyeah** [evant/kotlin-inject#282] opened 2023-08-06 05:37 UTC
Annotation based multiple bindings is generally supported in popular DI frameworks. We can just use `@Named`, `@Qualifer` to represent the binding.

Currently with `kotlin-inject`, to provide a named binding, we have to return a `Pair` object. 
Any plan to support annotation based binding?

**Comment by evant** [comment] 2023-08-08 00:24
Can you give an example on what exactly you are thinking and how it might be useful? The reason for the current implementation vs dagger's [multi-bindings](https://dagger.dev/dev-guide/multibindings.html#map-multibindings) is that a whole bunch of machinery doesn't need to be built to support keys at compile-time.

**Comment by wsxyeah** [comment] 2023-08-10 00:48
Yes, javax inject is exactly what I need.
Thanks.

**Comment by evant** [comment] 2023-08-28 02:24
Closing as a duplicate of #253 as that include a potential implementation of qualifiers

**Closed by evant** 2023-08-28 02:24 UTC
Labels: duplicate
